### ISSUE TITLE
FILES MISSING

### ISSUE THREAD

**Issue by peehoo1202** [hemanth-s17/Deep-Fish-Tracker-Network#2]
Unable to find **gt_vitbat.txt** and **det_vitbat.txt** files used in **ConvertIntoMot.py**

**Comment by hemanth-s17** [comment]
You can find them in the google drive folder. Please request the access to it by reaching out to the email mentioned in the readme file. ConvertIntoMot.py converts the gt.txt and det.txt files into MOT format required.

**Comment by peehoo1202** [comment]
We have already requested for access of the google drive folder on the mentioned email id. But we haven't received it till now. Can you please help us.
